// Type reduce
export const SET_COMMENTS_POST = 'SET_COMMENTS_POST'
export const ADD_COMMENT = 'ADD_COMMENT'

// Type saga
export const S_FETCH_COMMENTS_POST = 'S_FETCH_COMMENTS_POST'
export const S_CREATE_COMMENT_POST = 'S_CREATE_COMMENT_POST'
export const S_CREATE_CHILD_COMMENT = 'S_CREATE_CHILD_COMMENT'
export const S_DELETE_COMMENT = 'S_DELETE_COMMENT'
