// Type reduce
export const AUTH_SET_USER = 'AUTH_SET_USER'
export const AUTH_LOGIN_ERRORS = 'AUTH_LOGIN_ERRORS'
export const AUTH_LOGOUT_SUCCESSFUL = 'AUTH_LOGOUT_SUCCESSFUL'
export const AUTH_RESET_ERRORS = 'AUTH_RESET_ERRORS'

// Type saga
export const S_AUTH_SET_USER = 'S_AUTH_SET_USER'
export const S_AUTH_LOGIN_REQUEST = 'S_AUTH_LOGIN_REQUEST'
export const S_AUTH_LOGOUT_REQUEST = 'S_AUTH_LOGOUT_REQUEST'
