// Type reduce
export const AUTH_SET_USER = 'AUTH_SET_USER'
export const AUTH_LOGIN_ERRORS = 'AUTH_LOGIN_ERRORS'
export const AUTH_LOGOUT_SUCCESSFUL = 'AUTH_LOGOUT_SUCCESSFUL'
export const AUTH_LOGIN_SUCCESSFUL = 'AUTH_LOGIN_SUCCESSFUL'
export const AUTH_RESET_ERRORS = 'AUTH_RESET_ERRORS'
export const AUTH_LOGOUT_ERRORS = 'AUTH_LOGOUT_ERRORS'
export const AUTH_SIGNUP_ERRORS = 'AUTH_SIGNUP_ERRORS'
export const AUTH_SET_PROCESSING = 'AUTH_SET_PROCESSING'
export const UPDATE_USER_AVATAR = 'UPDATE_USER_AVATAR'
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'

// Type saga
export const S_AUTH_SET_USER = 'S_AUTH_SET_USER'
export const S_AUTH_LOGIN_REQUEST = 'S_AUTH_LOGIN_REQUEST'
export const S_AUTH_LOGOUT_REQUEST = 'S_AUTH_LOGOUT_REQUEST'
export const S_AUTH_SIGNUP_REQUEST = 'S_AUTH_SIGNUP_REQUEST'
export const S_AUTH_GET_ME = 'S_AUTH_GET_ME'
export const S_AUTH_UPDATE_ME = 'S_AUTH_UPDATE_ME'
